apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-crw

bases:
- ../manuela-team-rolebindings
- ../installplan-approver

resources:
- crw-namespace.yaml
- crw-operator-group.yaml
- crw-operator-sub.yaml
- crw-che-cluster.yaml