apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: manuela-dev

resources:
- ../../templates/manuela-openshift-dev



configMapGenerator:
- name: iot-frontend-cfg
  behavior: merge
  envs:
  - iot-frontend-configmap-config.properties
